language: python

python:
  - "2.7"

before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - >
    sudo apt-get install -qq --install-recommends debhelper debmake
    git-buildpackage pypy devscripts build-essential python-dev
    libsnmp-dev python-pika python-yaml python-mock

install:
  - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo pypy
  - rm -f setuptools-*.zip
  - sudo pip install coveralls
  - sudo ln -sf /usr/local/bin/coverage /usr/bin/

script:
  - make deb

after_success:
  - coveralls

before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key:
    secure: eISBbJNB5f9PrKz4fwrnNrvunJHX2cZh2XXnORJ6bO7AAecaMOKJk1IAZd4TDb0UCqwFbp96P5JmC8Q8H/k/dD7QRV2IfXbbZ4E82OS7A3fVJ9x+0nq9KjsXWvxli38+PgUtHsAo9JAxEY5yvMLAp9DcX2YqxcK7kzG1FvD50SA=
  file_glob: true
  file: "../*.deb"
  on:
    tags: true
    repo: dhtech/dhmon
