#!/usr/bin/env python
import daemon
import datetime
import dhmon
import multiprocessing as mp
import os
import shlex
import subprocess
import sys
import syslog
import time
import yaml


if len(sys.argv) != 4:
    print '%s: config daemon_id pidfile' % sys.argv[0]
    sys.exit(0)

config = yaml.load(file(sys.argv[1], 'r'))

PERIOD = config['period']
DAEMONS = int(config['number_of_daemons'])
ID = int(sys.argv[2])
OFFSET = (PERIOD / DAEMONS) * ID
PIDFILE = sys.argv[3]

def execute():
    processes = {}
    for script in config['scripts']:
        syslog.syslog(syslog.LOG_DEBUG, 'Running "%s"' % script)
        processes[script] = subprocess.Popen(script, shell=True)

    for cmdline, p in processes.iteritems():
        p.wait()
        if p.returncode != 0:
            syslog.syslog(syslog.LOG_WARNING,
                    'Process "%s" exited with error code %d' % (
                        cmdline, p.returncode))

def get_now():
    # Calculate our local 'now' with offset for our daemon index.
    return int(time.time() * 1000) - OFFSET

def new_cycle(start, jitter):
    execute()

    elapsed = get_now() - start
    if elapsed > int(float(PERIOD) * 0.9):
        syslog.syslog(syslog.LOG_CRIT,
            'Job dispatch took more than 90%% of the period, %d ms spent' % (
            elapsed, ))
    dhmon.metric('dhmon.%s.launcher.jitter' % config['name'], jitter)
    dhmon.metric('dhmon.%s.elapsed' % config['name'], elapsed)

def main():
    previous_cycle = 0
    start_up = True
    # Use a thread pool to amortize script latency
    thread_pool = mp.Pool(10)

    while True:
        # Calculate our local 'now' with offset for our daemon index.
        start = get_now()

        cycle = start / PERIOD
        jitter = start % PERIOD
        elapsed = 0
        if cycle != previous_cycle and not start_up:
            if jitter > 10000:
                syslog.syslog(syslog.LOG_CRIT,
                        'High jitter in job dispatcher, %d ms behind' % jitter)
            thread_pool.apply_async(new_cycle, (start, jitter))
            elapsed = get_now() - start

        time.sleep(float(min(PERIOD - elapsed, 100)) / 1000)
        previous_cycle = cycle
        start_up = False

with daemon.DaemonContext():
    with open(PIDFILE, 'w') as pidfile:
        pidfile.write(str(os.getpid()))
        pidfile.close()
    main()
