#!/usr/bin/env python2
import dhmon
import sqlite3
import sys
import time

import pingerlib

db = sqlite3.connect('/etc/ipplan.db')
cursor = db.cursor()
sql = ("SELECT name, ipv4_addr_txt FROM host")

# Mark current time as the datapoint time
timestamp = time.time()

hosts = {ipv4: host for host, ipv4 in cursor.execute(sql).fetchall()}
if '-d' in sys.argv:
  for ipv4, host in hosts.iteritems():
    print 'Sending %s %s' % (host, ipv4)
pingerlib.ping(hosts.keys())

metrics = []
try:
  for ip, secs, usecs in pingerlib.receive(1):
    host = hosts[ip]
    metrics.append(dhmon.BulkMetric(
        timestamp=timestamp, hostname=host,
        metric='ipplan-pinger.us', value=secs*1000000 + usecs))
    if '-d' in sys.argv:
      print '%s %s' % (host, secs*1000000 + usecs)
except zmq.error.Again:
  pass

# Save what we got
dhmon.metricbulk(metrics)
