#!/usr/bin/env python2
import argparse
import sqlite3
import sys
import time

import pingerlib


parser = argparse.ArgumentParser()
parser.add_argument(
    '-d', '--debug', dest='debug', action='store_const', const=True,
    default=False, help='print output to console')
parser.add_argument(
    '-dd', '--megadebug', dest='megadebug', action='store_const', const=True,
    default=False, help='print more output to console')
parser.add_argument(
    '-t', '--timeout', default=1, type=int, help='timeout')
args = parser.parse_args()

if args.megadebug:
  import logging
  logging.basicConfig(level=logging.DEBUG)

db = sqlite3.connect('/etc/ipplan.db')
cursor = db.cursor()
sql = ("SELECT name, ipv4_addr_txt FROM host")

# Mark current time as the datapoint time
timestamp = time.time()

hosts = {ipv4: host for host, ipv4 in cursor.execute(sql).fetchall()}
if args.debug:
  for ipv4, host in hosts.iteritems():
    print >>sys.stderr, 'Sending %s %s' % (host, ipv4)
pingerlib.ping(hosts.keys())

metrics = []
for ip, secs, usecs in pingerlib.receive(args.timeout):
  host = hosts[ip]
  print 'icmp_rtt_seconds{{target="{0}"}} {1} {2}'.format(
      host, float(secs*1000000 + usecs)/10**6, int(timestamp*1000))
