#!/usr/bin/env python2
import dhmon
import socket
import sqlite3
import sys
import time

import pingerlib

this_host = socket.gethostname()

db = sqlite3.connect('/etc/ipplan.db')
cursor = db.cursor()
sql = ("SELECT name, ipv4_addr_txt FROM host")

# Mark current time as the datapoint time
timestamp = time.time()

hosts = {ipv4: host for host, ipv4 in cursor.execute(sql).fetchall()}
pingerlib.ping(hosts.keys())

metrics = []
try:
  for ip, secs, usecs in pingerlib.receive(1):
    host = hosts[ip]
    metrics.append(dhmon.BulkMetric(
        timestamp=timestamp, hostname=host,
        metric='ipplan-pinger.%s.us' % this_host,
        value=secs*1000000 + usecs))
except zmq.error.Again:
  pass

# Save what we got
dhmon.metricbulk(metrics)
