#!/bin/bash -xe

IP=$(sqlite3 /etc/ipplan.db \
  "SELECT ipv4_addr_txt FROM host WHERE name = '$(hostname -f)'")

cd $(dirname $0)

cat << EOF > /etc/apt/sources.list.d/cassandra.list
deb http://www.apache.org/dist/cassandra/debian 20x main
EOF

cat data/cassandra-apt.pub | apt-key add -
apt-get update

apt-get install -y cassandra openjdk-7-jre-headless

# TODO(bluecmd): Change cluster name from 'Test Cluster' to 'dhmon cassandra'
sed -i "s/listen_address: localhost/listen_address: $IP/" /etc/cassandra/cassandra.yaml
sed -i "s/rpc_address: localhost/rpc_address: $IP/" /etc/cassandra/cassandra.yaml
sed -i "s/- seeds: \"127.0.0.1\"/- seeds: \"metricstore,localhost\"/" /etc/cassandra/cassandra.yaml

service cassandra restart
