#!/bin/bash -xe

apt-get -t install redis-server
gem install flapjack

curl -X DELETE "http://localhost:3081/contacts/1"

curl -X POST -H "Content-Type: application/vnd.api+json" -d \
 '{
    "contacts": [
      {
        "id": 1,
        "first_name": "Dreamhack",
        "last_name": "Noc",
        "email": "XXXX@YYYYYYY",
        "timezone": "Europe/Stockholm"
      }
    ]
  }' \
 http://localhost:3081/contacts

curl -X POST -H "Content-Type: application/vnd.api+json" -d \
 '{
    "media": [
      {
        "type" : "email",
        "address" : "XXXX@YYYYYYYY",
        "interval" : 10,
        "rollup_threshold" : null
      },
      {
        "type" : "udp",
        "address" : "XX:YY",
        "interval" : 1,
        "rollup_threshold" : null
      }
    ]
  }' \
 http://localhost:3081/contacts/1/media

NOTIFICATION_ID=$(curl -s http://localhost:3081/notification_rules | \
  sed 's/.*"id":"\([a-f0-9-]*\)".*/\1/')

curl -X DELETE \
    "http://localhost:3081/notification_rules/${NOTIFICATION_ID}"

curl -X POST -H "Content-Type: application/vnd.api+json" -d \
 '{
    "notification_rules": [
      {
        "warning_media": [
          "email",
          "udp"
        ],
        "critical_media": [
          "email",
          "udp"
        ]
      }
    ]
  }' \
http://localhost:3081/contacts/1/notification_rules

curl -X POST -H "Content-type: application/vnd.api+json" -d \
 '{
    "entities": [
      {
        "id": "ALL",
        "name": "ALL",
        "contacts": [ "1" ]
      }
    ]
  }' \
 http://localhost:3081/entities
