#!/usr/bin/env python
import dhmon
import sys

if len(sys.argv) != 5:
  print "%s: timestamp hostname metric value" % sys.argv[0]
  sys.exit(0)

value = sys.argv[4]

if len(value) == 0:
  sys.exit(0)

dhmon.metric(timestamp=sys.argv[1], hostname=sys.argv[2], metric=sys.argv[3],
             value=value)
