#!/usr/bin/env python
import dhmon
import socket
import sys
import time

if len(sys.argv) < 3:
  print "%s: [timestamp] [hostname] metric value" % sys.argv[0]
  sys.exit(0)

args = sys.argv[1:]
args.reverse()
timestamp = int(time.time())
hostname = socket.getfqdn()

if len(args) == 4:
    timestamp = int(args.pop())
if len(args) == 3:
    hostname = args.pop()

metric = args.pop()
value = args.pop()

if len(value) == 0:
  sys.exit(0)

value = eval(value)
if value is None:
  sys.exit(0)

# TODO(bluecmd): Move this when we enumerate paths correctly in Cynaite
dhmon.connect(dhmon.CarbonBackend)
if not dhmon.metric(metric, value, timestamp=timestamp, hostname=hostname):
  sys.exit(1)
