#!/bin/bash

# Save timestamp before ping, this should be less of a lie than having it after.
echo "TIMESTAMP=$(date +'%s')"

PINGERHOST=$(hostname)
for row in $(sqlite3 /etc/ipplan.db 'SELECT name FROM host' \
              | xargs -P0 -n 1 fping -r 1 -i 10 -e 2> /dev/null \
              | awk '{ print $1 $4 }' | sed 's/(/=/')
do
  HOST=$(echo $row | cut -f 1 -d '=')
  LATENCY=$(echo $row | cut -s -f 2 -d '=')
  if [[ ! -z "$LATENCY" ]]; then
  	echo "$HOST|ipplan-pinger.$PINGERHOST.us|$LATENCY * 1000"
  fi
done
