#!/bin/bash

# Save timestamp before ping, this should be less of a lie than having it after.
TIMESTAMP=$(date +'%s')
for row in $(sqlite3 /etc/ipplan.db 'SELECT name FROM host' \
              | xargs fping -r 1 -i 10 -e 2> /dev/null \
              | awk '{ print $1 $4 }' | sed 's/(/=/')
do
  HOST=$(echo $row | cut -f 1 -d '=')
  LATENCY=$(echo $row | cut -s -f 2 -d '=')
  dhmon-metric "$TIMESTAMP" "$HOST" 'ipplan-pinger' "$LATENCY"
done
