#!/bin/bash

IFS='
'
for row in $(stat --printf "%n %Y %s\n" /var/log/dh/*/all.log)
do
  filename=$(basename $(dirname $(echo $row | awk '{print $1}')))
  stamp=$(echo $row | awk '{print $2}')
  size=$(echo $row | awk '{print $3}')

  now=$(date +"%s")
  delta=$((now-stamp))
  

  if ! echo "${filename}" | grep '\.' -q; then
    # TODO(bluecmd): we probably want full fqdn from servers instead
    host="$filename.event.dreamhack.se"
  else
    host="$filename"
  fi
  echo "$host|syslog.updated|$delta * 1000"
  echo "$host|syslog.size|$size"
done
