#!/bin/bash

cd $(dirname $0)
timestamp=redis-$(date +'%Y-%m-%d_%H%M')
mkdir $timestamp
cd $timestamp

for key in $(redis-cli -h dhmon keys '*' | cut -f 2)
do
  echo "Dumping $key"
  redis-cli -h dhmon zrange $key 0 -1 withscores > $key.lst
done

echo 'Compressing'

cd ..
tar -cJf $timestamp.tar.xz $timestamp
rm -r $timestamp

echo 'Done'
